server:
  port: 8702
spring:
  application:
    name: practice-system-web
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/practice?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    mapUnderscoreToCamelCase: false
eureka:
  instance:
    preferIpAddress: true
    ipaddress: localhost
    instance-id: ${spring.application.name}:${eureka.instance.ipaddress}:${server.port}
    hostname: ${spring.application.name}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.ipaddress}:8701/eureka
patterns:
  detail:
    - /user/login
    - /swagger-ui/**
    - /swagger-resources/**
    - /v3/**
ribbon:
  eureka:
    enabled: true # 使用Eureka作为服务发现
  MaxAutoRetries: 1 # 重试其他服务器的次数
  MaxAutoRetriesNextServer: 1 # 切换到下一个服务器的最大重试次数
  OkToRetryOnAllOperation: true # 对所有操作请求都进行重试
  ReadTimeout: 5000 # 请求读取超时时间
  ConnectTimeout: 3000 # 请求连接超时时间
logging:
  level:
    com.liwx: DEBUG
    root: debug
oauth:
  checkTokenUri: http://localhost:8708/oauth/check_token
  clientId: clientC
  clientSecret: 123456
  resourceId: sys
  tokenUri: http://localhost:8708/token