eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8701/eureka
  instance:
    hostname: gateway-server
    status-page-url: http://${eureka.instance.ip-address}:${server.port}/actuator/info
    ip-address: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname} ${eureka.instance.ip-address}:${server.port}
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #routes:
      #  -id: WEB-CLIENT
      #  uri: lb://WEB-CLIENT
      #  predicates:
      #    - Path=/*

server:
  port: 8703
management:
  endpoints:
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"