spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/practice?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  application:
    name: practice-gateway
  cloud:
    discovery:
      locator:
        enabled: true  # 启用服务发现定位器
        lowerCaseServiceId: true  # 将服务ID转换为小写
    gateway:
      routes:
        - id: practice-system-web-route
          uri: lb://practice-system-web # 使用服务发现来路由
          predicates:
            - Path=/user/**
        - id: practice-order-route
          uri: lb://practice-order # 使用服务发现来路由
          predicates:
            - Path=/order/**
server:
  port: 80

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8701/eureka/  # 指向Eureka服务端的地址
  instance:
    ipAddress: localhost
    preferIpAddress: true  # 使用IP地址而非hostname注册服务
    hostname: ${spring.application.name}
logging:
  level:
    com.liwx: debug
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG